-- venuu venues upsert  |  generated 2026-06-02
-- Ground-truth coordinates. Adjust table/column names to match your schema if different.
-- Assumes a `venues` table keyed on a unique `slug`. If you key on id/name instead,
-- change the INSERT columns and the ON CONFLICT target accordingly.

INSERT INTO venues (slug, name, city, neighborhood, address, latitude, longitude, is_partner, description) VALUES
  ('lower-deck','Lower Deck','Tampa','Harbour Island','601 S Harbour Island Blvd Ste 110, Tampa, FL 33602',27.9379500,-82.4552000,true,'Laid-back dockside waterfront bar at the marina level of Harbour Island with panoramic Tampa skyline views, raw oysters, craft cocktails, and live music; the casual coastal escape just below American Social.'),
  ('american-social','American Social','Tampa','Harbour Island','601 S Harbour Island Blvd #107, Tampa, FL 33602',27.9384058,-82.4548630,false,'Spacious waterfront bar-and-kitchen on Harbour Island with Tampa skyline views, indoor/outdoor bars, Taco Tuesday, and weekend nightlife energy; lively, stylish, busy, loud, and fun.'),
  ('boulon','Boulon','Tampa','Water Street','1001 Water St, Tampa, FL 33602',27.9437675,-82.4500198,false,'Bright all-day French brasserie and bakery in Water Street serving beef tartare, lobster bisque, and burlesque martinis; lively, attentive, and stylish, a special-occasion spot.'),
  ('predalina','Predalina','Tampa','Water Street','1001 E Cumberland Ave, Tampa, FL 33602',27.9448680,-82.4500045,false,'Glamorous Mediterranean coastal restaurant and after-dark cocktail lounge on Water Street, all hand-laid mosaics, olive trees, and a gold disco ball over a painted dance floor.'),
  ('511-franklin','511 Franklin','Tampa','Downtown','513 N Franklin St, Tampa, FL 33602',27.9490216,-82.4582075,false,'Upscale-casual downtown craft cocktail bar with a strong bourbon selection, well-made old fashioneds, happy-hour specials, and DJ nights; classy yet welcoming, drawing a 23+ after-dark professional crowd.'),
  ('echo','Echo Downtown','Tampa','Downtown','914 N Franklin St, Tampa, FL 33602',27.9518696,-82.4600740,false,'Downtown Franklin St late-night dance club spinning R&B and Latin on weekends only with cover charges; energetic crowd and music.'),
  ('delta','Delta Downtown','Tampa','Downtown','912 N Franklin St, Tampa, FL 33602',27.9517715,-82.4600305,false,'Multi-floor downtown nightclub running three zones of music, EDM/house outdoors, hip-hop on the first floor, Spanish upstairs, open Friday and Saturday nights with cover charges; vibrant and danceable.'),
  ('m-bird','M.Bird','Tampa','Tampa Heights','1903 Market St, Tampa, FL 33602',27.9609900,-82.4642862,false,'Rooftop American restaurant and bar atop Armature Works with sweeping Tampa Bay views, friendly attentive staff, a DJ-driven night scene, and solid food; a lively special-occasion and celebration spot, busy on weekends.'),
  ('armature-works','Armature Works','Tampa','Tampa Heights','1910 N Ola Ave, Tampa, FL 33602',27.9609343,-82.4642724,false,'Historic 1910 streetcar warehouse turned Tampa Heights food hall and riverside entertainment destination, family-friendly by day and a nightlife hub by night, with M.Bird on the roof.'),
  ('sunset-rodeo','Sunset Rodeo','Tampa','SoHo (S Howard)','302 S Howard Ave, Tampa, FL 33606',27.9416843,-82.4827188,false,'Nashville-inspired SoHo live-music bar with weekly country and Southern-rock acts, standout decor, an outdoor patio, brunch, VIP tables, and a 23+ policy; high-energy with Nashville hot chicken and smash burgers.'),
  ('the-grove','The Grove','Tampa','SoHo (S Howard)','406 S Howard Ave, Tampa, FL 33606',27.9405769,-82.4827815,false,'SoHo bar with DJs, live reggae, well-made bar drinks, and excellent outdoor service; clean, entertaining, and friendly.'),
  ('macdintons','MacDinton''s','Tampa','SoHo (S Howard)','405 S Howard Ave, Tampa, FL 33606',27.9405322,-82.4831814,false,'SoHo''s biggest Irish pub and nightlife institution with multiple bars, DJs, karaoke, trivia, daily specials, and a sports patio; high-energy college-adjacent crowd.'),
  ('corner-bar','Corner Bar','Tampa','SoHo (S Howard)','402 S Howard Ave, Tampa, FL 33606',27.9409084,-82.4828092,false,'Chill, dog-friendly SoHo corner bar with weekend DJs, Tuesday karaoke and trivia, cigar-friendly outdoor seating, and Sunday $5 drink specials; great service and reasonable prices in a relaxed neighborhood vibe.'),
  ('the-patio','The Patio','Tampa','SoHo (MacDill Ave)','421 S MacDill Ave, Tampa, FL 33609',27.9400902,-82.4935891,false,'Easygoing multi-level SoHo patio bar and Bills Backers spot with three bars, a food truck, darts, plenty of TVs, and reasonable prices; chill, electric on game days, with limited parking.'),
  ('meat-market','Meat Market','Tampa','Hyde Park','1606 W Snow Ave, Tampa, FL 33606',27.9358980,-82.4760815,false,'Upscale Hyde Park steakhouse with prime cuts, sushi, lobster mac, and craft cocktails in a trendy, elegant indoor-outdoor setting; a popular special-occasion destination.'),
  ('blind-goat','The Blind Goat','Tampa','South Tampa (Henderson)','4106 Henderson Blvd, Tampa, FL 33629',27.9278699,-82.5122459,false,'Lively, dog-friendly South Tampa bar-and-grill with elevated bar food, pizzas, wings, the Goat Drip cocktail, dart boards, pool, and weekly trivia and bingo; loud, younger FSU-leaning crowd, owner-run feel.'),
  ('red-dog','Red Dog','Tampa','South Tampa (Bay to Bay)','3311 W Bay to Bay Blvd, Tampa, FL 33629',27.9199580,-82.4981003,false,'Casual neighborhood bar with billiards, darts, cold beer, strong drinks, and good burgers; friendly local vibe and a unique atmosphere.'),
  ('dead-bobs','Dead Bob''s','Tampa','South Tampa (Westshore)','3681 S Westshore Blvd, Tampa, FL 33629',27.9090070,-82.5269904,false,'Unpretentious, budget-friendly South Tampa fisherman''s sports bar, open 11am-3am daily, packed with TVs and serving standout burgers, wings, French dips, and mahi bites; lively, friendly, and beloved by locals.'),
  ('five-bucks-drinkery','Five Bucks Drinkery','St. Petersburg','Downtown (Central Ave)','247 Central Ave, St. Petersburg, FL 33701',27.7713413,-82.6363935,false,'Busy Central Ave sports bar and grill open 11am-3am daily with sidewalk seating, value-priced food and drinks, famous fries, and fast friendly bartenders; reliable lunch and late-night downtown staple.'),
  ('banana-hammock','Banana Hammock','St. Petersburg','Downtown (Central Ave)','247 Central Ave, St. Petersburg, FL 33701',27.7715710,-82.6364159,false,'Laid-back outdoor bar tucked behind Five Bucks with cheap $5 cans, a smoky ''illegal margarita,'' wings, fries, and French dips; relaxed street-side seating and music away from the noise.'),
  ('birchwood-canopy','The Canopy at the Birchwood','St. Petersburg','Beach Drive','340 Beach Dr NE, St. Petersburg, FL 33701',27.7760139,-82.6320345,false,'Rooftop bar atop the Birchwood with panoramic Old Tampa Bay and downtown views, excellent espresso martinis, and prime sunset timing; elegant and festive.'),
  ('cane-and-barrel','Cane & Barrel','St. Petersburg','Downtown (2nd St)','110 2nd St N, St. Petersburg, FL 33701',27.7726847,-82.6357233,false,'Relaxed rooftop bar atop the AC Marriott with two full bars, Latin-Caribbean tapas, empanadas, yuca fries, peekaboo bay views, and DJ or steel-drum nights; calm hidden-gem ambiance.'),
  ('copper-shaker','Copper Shaker','St. Petersburg','Downtown (1st Ave)','169 1st Ave N, St. Petersburg, FL 33701',27.7723137,-82.6349515,false,'Speakeasy-style craft cocktail bar with a premium whiskey selection, hand-crafted old fashioneds, truffle fries, and Taco Tuesday; bartenders who remember your name, classy and chill, open till 3am nightly.'),
  ('crafty-squirrel','Crafty Squirrel','St. Petersburg','Downtown (Central Ave)','259 Central Ave, St. Petersburg, FL 33701',27.7713527,-82.6365966,false,'Versatile Central Ave spot that''s a cozy sports pub by day and a late-night dance bar by night, with two-for-one happy hours, bottomless mimosas, bottle service, and a flavor-forward new menu.'),
  ('fergs','Ferg''s Sports Bar','St. Petersburg','Edge District','1320 Central Ave, St. Petersburg, FL 33705',27.7708789,-82.6521900,false,'Sprawling, nationally top-rated sports bar near Tropicana Field with hundreds of TVs, $5 game-day beers, famous wings, live music, two dog parks, and a tunnel toward the Trop.'),
  ('flute-and-dram','Flute & Dram','St. Petersburg','Beach Drive','234 Beach Dr NE, St. Petersburg, FL 33701',27.7743792,-82.6326767,false,'Polished Beach Drive whiskey-and-champagne lounge with cigars, caviar, an in-house humidor, 25%-off-whiskey Thursdays, live music, and prime waterfront people-watching; one of the best-located bars on the strip.'),
  ('goodnight-john-boy','Good Night John Boy','St. Petersburg','Downtown (2nd St)','16 2nd St N, St. Petersburg, FL 33701',27.7716018,-82.6357291,false,'High-energy 1970s disco-themed dance bar with a checkerboard dance floor, retro decor, and a mix of 70s hits and newer beats; reasonably priced, all-ages-of-adult fun, extremely packed after 9pm.'),
  ('jannus-live','Jannus Live','St. Petersburg','Downtown (Jannus Landing)','200 1st Ave N Ste 206, St. Petersburg, FL 33701',27.7719257,-82.6362710,false,'Intimate historic open-air courtyard concert venue hosting surprisingly big touring acts with great acoustics, no bad sightlines, a balcony, and multiple bars; minimal seating, standing-room shows.'),
  ('mandarin-hide','Mandarin Hide','St. Petersburg','Downtown (Central Ave)','231 Central Ave, St. Petersburg, FL 33701',27.7713667,-82.6362014,false,'Rustic, dimly lit craft cocktail lounge known for expertly built old fashioneds and the best spicy margarita around, with vintage decor, live music, and $9 weeknight specials; conversational until late, open till 3am.'),
  ('mary-margarets','Mary Margaret''s','St. Petersburg','Downtown (3rd St)','29 3rd St N, St. Petersburg, FL 33701',27.7718144,-82.6368227,false,'Authentic downtown Irish pub with flawless Guinness pours, full Irish breakfast, banger-and-mash, and mustard-slaw sandwiches; lively daily with a sharp bar staff, open till 2-2:30am.'),
  ('my-rich-uncle','My Rich Uncle','St. Petersburg','Downtown (1st Ave)','260 1st Ave N, St. Petersburg, FL 33701',27.7719542,-82.6365810,false,'Weekend-only high-energy nightclub-style bar open Friday-Saturday 8pm-2:30am with thumping DJ sets, bottle service, and dedicated VIP hosts; cinematic party atmosphere with a dressed-up crowd.'),
  ('oak-and-stone','Oak & Stone','St. Petersburg','Downtown (Central Ave)','199 Central Ave, St. Petersburg, FL 33701',27.7714566,-82.6352435,false,'Casual craft-pizza restaurant with a signature self-pour beer wall, tons of taps, gluten-free options, and sports on TV; affordable, relaxed, and walkable to the St. Pete Pier.'),
  ('one-night-stand','The One Night Stand','St. Petersburg','Downtown (1st Ave)','149 1st Ave N, St. Petersburg, FL 33701',27.7722795,-82.6348431,false,'Comfortably worn-in country dive bar centered on a mechanical bull, with country music, a 25% military discount, and a welcoming community spirit; open till 3am.'),
  ('park-and-rec','Park & Rec DTSP','St. Petersburg','Downtown (4th St)','100 4th St S, St. Petersburg, FL 33701',27.7700162,-82.6382071,false,'Big playful gastro-bar and adult arcade with pool, games, cornhole, a wall of TVs, self-poured bottomless mimosas, $25 all-you-can-eat snacks, free trivia, and a dog-friendly, game-day-friendly vibe.'),
  ('pier-teaki','Pier Teaki','St. Petersburg','St. Pete Pier','800 2nd Ave NE 5th Floor, St. Petersburg, FL 33701',27.7735968,-82.6224926,false,'Open-air rooftop tiki bar atop the St. Pete Pier with sweeping water, city, and dolphin views, creative tiki cocktails, and shareable plates like lobster-chorizo empanadas; chill tropical mood.'),
  ('pour-judgement','Pour Judgement','St. Petersburg','Downtown (Central Ave)','269 Central Ave, St. Petersburg, FL 33701',27.7714168,-82.6367583,false,'Central Ave bar built around an extensive menu-book of shots and themed drink specials, with engaging bartenders and fun start-the-night energy, open till 3am.'),
  ('saigon-blonde','Saigon Blonde','St. Petersburg','Downtown (Central Ave)','265 Central Ave, St. Petersburg, FL 33701',27.7713936,-82.6367072,false,'Funky Vietnam/New Orleans-themed lounge on the Central Ave drag with eclectic war-era decor, house and techno DJs, rum old fashioneds, hemp cocktails, and THC seltzers; chill early, lively and danceable late.'),
  ('sparrow','Sparrow','St. Petersburg','Edge District','1234 Central Ave, St. Petersburg, FL 33705',27.7709681,-82.6510648,false,'Rooftop Asian-leaning restaurant and cocktail bar atop the Moxy with views toward Tropicana Field, pork bao buns, sushi, lobster mac, and tequila-espresso martinis; stylish weekend energy.'),
  ('tequila-daisy','Tequila Daisy','St. Petersburg','Downtown (1st Ave)','120 1st Ave N, St. Petersburg, FL 33701',27.7719355,-82.6345176,false,'Compact downtown tequila bar boasting one of the world''s largest tequila collections, custom-built cocktails, hibiscus palomas, and guided tastings; friendly fast-paced bartenders and a great meet-up size, open till 3am.'),
  ('the-landing','The Landing','St. Petersburg','Downtown (Jannus Landing)','200 1st Ave N, St. Petersburg, FL 33701',27.7719201,-82.6357797,false,'Loft bar above Jannus Live with great city views, local DJ events, a full bar, and Sunday-Funday shot specials; cool hideaway vibe.'),
  ('trailer-daddy','Trailer Daddy','St. Petersburg','Downtown (Central Ave)','217 Central Ave, St. Petersburg, FL 33701',27.7713218,-82.6360721,false,'Tongue-in-cheek trailer-park-themed bar with creative cocktails, playful shots like the American Pie and PB&J, and cheesesteaks; great music, genuine staff, and a fresh, lively concept, open weekends till 2am.'),
  ('tryst','Tryst','St. Petersburg','Beach Drive','240 Beach Dr NE, St. Petersburg, FL 33701',27.7745140,-82.6326825,false,'Eclectic Beach Drive gastro-lounge with a Mediterranean-French menu, fish tacos, bottomless mimosas, hookah, Tito''s on tap, and live music; prime patio people-watching and fast service, open till 3am.'),
  ('detroit-201','Detroit 201','St. Petersburg','Downtown (Central Ave)','201 Central Ave, St. Petersburg, FL 33701',27.7713654,-82.6357291,false,'Tiny Central Ave corner cocktail bar with nightly live music, a string-lit patio, an abundant drink list, $5 old fashioneds, and barrel-aged ales; intimate, vibey, with a lovely on-site owner.'),
  ('welcome-to-the-farm','Welcome To The Farm','St. Petersburg','Downtown (1st Ave)','242 1st Ave N, St. Petersburg, FL 33701',27.7718136,-82.6363795,false,'Popular downtown country bar with live country music, weekend outdoor DJs, multiple bars, Thursday karaoke, free military entry, and a late-night sports-bar connection; a local home base.')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  city = EXCLUDED.city,
  neighborhood = EXCLUDED.neighborhood,
  address = EXCLUDED.address,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  is_partner = EXCLUDED.is_partner,
  description = EXCLUDED.description;

-- Venues to REMOVE (not in the verified list):
-- DELETE FROM venues WHERE name ILIKE 'Waterstreet' OR name ILIKE 'The Saloon';
-- Dupes consolidated to one row each (delete the redundant copies if they exist):
--   'Grove Soho'  -> keep slug 'the-grove'
--   'Corner Bar SoHo' -> keep slug 'corner-bar'
--   '5 Buck's Drinkery' -> keep slug 'five-bucks-drinkery'