-- ═══════════════════════════════════════════════════════════════
-- 00027_venny_foundation.sql
--
-- Foundation tables for the map-resident Venny agent:
--   • user_preferences        — long-lived taste profile per user
--   • venny_conversations     — one row per user "thread"
--   • venny_messages          — every user/assistant/tool message
--
-- Preferences keys match the set get_user_taste / set_user_preference
-- tools expose: age, music_taste, typical_budget, dress_style,
-- group_size_typical, vibes_liked, vibes_disliked, home_city. Schema
-- is liberal on column types so the edge function can write
-- partial profiles without forcing every field up front.
--
-- venny_messages.content is JSONB — Anthropic tool calls store the
-- tool_use / tool_result blocks inline so a full message history
-- replay reconstructs the agent state losslessly.
--
-- Wrapped in BEGIN/COMMIT, idempotent.
-- ═══════════════════════════════════════════════════════════════

BEGIN;

-- ───────────────────────────────────────────────────────────────
-- user_preferences — one row per Supabase auth user
-- ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_preferences (
  user_id            uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  age                int,
  music_taste        text,        -- free-form string ("hip hop, country")
  typical_budget     text,        -- '$' | '$$' | '$$$'
  dress_style        text,        -- free-form
  group_size_typical int,
  vibes_liked        text[]  NOT NULL DEFAULT ARRAY[]::text[],
  vibes_disliked     text[]  NOT NULL DEFAULT ARRAY[]::text[],
  home_city          text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_preferences_updated
  ON public.user_preferences (updated_at DESC);

ALTER TABLE public.user_preferences ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='public' AND tablename='user_preferences' AND policyname='Users read own preferences'
  ) THEN
    CREATE POLICY "Users read own preferences"
      ON public.user_preferences FOR SELECT TO authenticated
      USING (auth.uid() = user_id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='public' AND tablename='user_preferences' AND policyname='Users upsert own preferences'
  ) THEN
    CREATE POLICY "Users upsert own preferences"
      ON public.user_preferences FOR INSERT TO authenticated
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='public' AND tablename='user_preferences' AND policyname='Users update own preferences'
  ) THEN
    CREATE POLICY "Users update own preferences"
      ON public.user_preferences FOR UPDATE TO authenticated
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

GRANT SELECT, INSERT, UPDATE ON public.user_preferences TO authenticated;

-- ───────────────────────────────────────────────────────────────
-- venny_conversations — one row per Venny "thread"
-- ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.venny_conversations (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  city        text NOT NULL,
  title       text,                 -- optional summary auto-generated by Venny
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_venny_conversations_user_updated
  ON public.venny_conversations (user_id, updated_at DESC)
  WHERE user_id IS NOT NULL;

ALTER TABLE public.venny_conversations ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='public' AND tablename='venny_conversations' AND policyname='Users read own conversations'
  ) THEN
    CREATE POLICY "Users read own conversations"
      ON public.venny_conversations FOR SELECT TO authenticated
      USING (auth.uid() = user_id);
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='public' AND tablename='venny_conversations' AND policyname='Users create own conversations'
  ) THEN
    CREATE POLICY "Users create own conversations"
      ON public.venny_conversations FOR INSERT TO authenticated
      WITH CHECK (auth.uid() = user_id OR user_id IS NULL);
  END IF;
END $$;

GRANT SELECT, INSERT, UPDATE ON public.venny_conversations TO authenticated;

-- ───────────────────────────────────────────────────────────────
-- venny_messages — every message in a conversation
-- ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.venny_messages (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL REFERENCES public.venny_conversations(id) ON DELETE CASCADE,
  role            text NOT NULL CHECK (role IN ('user', 'assistant', 'tool')),
  content         jsonb NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_venny_messages_conversation_created
  ON public.venny_messages (conversation_id, created_at);

ALTER TABLE public.venny_messages ENABLE ROW LEVEL SECURITY;

-- Users read messages from conversations they own. RLS subquery is fine
-- here — conversation_id is indexed and venny_conversations is small.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname='public' AND tablename='venny_messages' AND policyname='Users read own messages'
  ) THEN
    CREATE POLICY "Users read own messages"
      ON public.venny_messages FOR SELECT TO authenticated
      USING (
        conversation_id IN (
          SELECT id FROM public.venny_conversations
          WHERE user_id = auth.uid()
        )
      );
  END IF;
END $$;

GRANT SELECT ON public.venny_messages TO authenticated;
-- INSERT happens via service_role from the edge function only.

-- ───────────────────────────────────────────────────────────────
-- Verify
-- ───────────────────────────────────────────────────────────────
DO $$
DECLARE
  pref_ok boolean;
  conv_ok boolean;
  msg_ok  boolean;
  pol_n   int;
BEGIN
  SELECT EXISTS (SELECT 1 FROM information_schema.tables
    WHERE table_schema='public' AND table_name='user_preferences') INTO pref_ok;
  SELECT EXISTS (SELECT 1 FROM information_schema.tables
    WHERE table_schema='public' AND table_name='venny_conversations') INTO conv_ok;
  SELECT EXISTS (SELECT 1 FROM information_schema.tables
    WHERE table_schema='public' AND table_name='venny_messages') INTO msg_ok;
  SELECT COUNT(*) INTO pol_n FROM pg_policies
    WHERE schemaname='public' AND tablename IN ('user_preferences','venny_conversations','venny_messages');

  RAISE NOTICE '═══ Migration 00027 complete ═══';
  RAISE NOTICE '  user_preferences:      %', CASE WHEN pref_ok THEN 'OK' ELSE 'MISSING' END;
  RAISE NOTICE '  venny_conversations:   %', CASE WHEN conv_ok THEN 'OK' ELSE 'MISSING' END;
  RAISE NOTICE '  venny_messages:        %', CASE WHEN msg_ok  THEN 'OK' ELSE 'MISSING' END;
  RAISE NOTICE '  RLS policies installed: %', pol_n;
END $$;

COMMIT;
